# Generated by Django 3.2.12 on 2022-03-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlibrary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'UserLibraries'},
        ),
    ]
